services:
    api:
        # image: ghcr.io/kelseywilliams/api.kelseywilliams.co:main
        build: .
        init: true # Injects init system (Tini) that handles PID 1 tasks. (Graceful shutdown)
        container_name: api
        environment:                 # <- the analog of the api-config ConfigMap
            PORT: "3028"
            USER: "588a4c44508b53764ddbfa2db86996e470b0a4e0f5212840f586f7643f0d791e"
            ADMIN: "28ee1b68e6b7ff1683ab98170c49f3ca5a686aeb65c0741e5c95d3b3b1932fdd"
            TOKEN_EXPIRY_MINS: "20"
            API_DOMAIN: "proxy:80/api/"
            DOMAIN: "localhost"
        secrets:
            - mailjet_api_key
            - mailjet_secret
            - jwt_private
            - jwt_public
            - postgres_worker_secret
            - postgres_readonly_secret
            - redis_secret
        networks:
            - site
        volumes:
            - ./home/logs:/logs
        ports:
            - "3028:3028"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3028/healthz"]
            interval: 10s
            timeout: 3s
            start_period: 30s
            retries: 3
        #stop_grace_period: 15s

secrets:
    mailjet_api_key:
        file:  ./secrets/mailjet_api_key.txt
    mailjet_secret:
        file: ./secrets/mailjet_secret.txt
    jwt_private:
        file: ./secrets/jwt_private.txt
    jwt_public:
        file: ./secrets/jwt_public.txt
    postgres_worker_secret:
        file: ./secrets/postgres_worker_secret.txt
    postgres_readonly_secret:
        file: ./secrets/postgres_readonly_secret.txt
    redis_secret:
        file: ./secrets/redis_secret.txt

networks:
    site:
        external: true

